### ISSUE TITLE
Scoring

### ISSUE THREAD

**Issue by memoakten** [memo/BattleOfBozork#2]
@solar-1992 @colormotor 
Because we have missiles, asteroids and tails, I think we need a new scoring system. I recommend a 'health' based system.
- you start at health 100%
- getting hit by a missile drops your health by 1 point
- getting hit by an asteroid drops your health by 10 points
- getting hit by a tail drops your health by 20 points
  or something, what do y'all think?

**Comment by piers-williams** [comment]
this is a good idea - easier for human beings to understand :p
