### ISSUE TITLE
Unique csv file names

### ISSUE THREAD

**Issue by memoakten** [memo/BattleOfBozork#3]
I've added a ParameterManager class, and SimpleBattle has an instance of it called params.

SimpleBattle.playGame(...) takes a boolean as the last parameter, if it's true, the parameters are randomized before running the game.

We need unique names for each CSV. i suggest we just timestamp the filenames, and then dump the parameters into a CSV as well.

ParameterManager.getData(names, values) fills in the two arrays with the parameter names and values. So they can be dumped into a file. 
@solar-1992 @colormotor

**Comment by colormotor** [comment]
Just a note, we should remove white spaces between names and commas as Spyder considers them as part of the label...
